---
title: "Twitter Analytics of Linux Open Source Summit"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=F,message=F, echo=F}
##Install Packages
#install.packages("tm")  # for text mining
#install.packages("SnowballC") # for text stemming
#install.packages("wordcloud") # word-cloud generator 
#install.packages("RColorBrewer") # color palettes
#devtools::install_github('cttobin/ggthemr')
library(ggplot2)
library(tidyr)
library(dplyr)
library(devtools)
library(ggthemr)
##Load Require Library
library(tm)
library(SnowballC)
library(RColorBrewer)
library(wordcloud)

ggthemr_reset()
dust_theme <- ggthemr('light', set_theme = FALSE)
```
## Sentiment in 24 Hour of Aug30
```{r warning=F,message=F,echo=F}
cls <- c(hour="numeric")
t_data <- read.csv('tweets_sentiment.csv', stringsAsFactors=FALSE )

ggplot(data = t_data, aes(x=hour, fill = sentiment)) + 
  geom_bar() + 
  scale_x_continuous(breaks = seq(0,23, 1)) +
  ylab("sentiment") + 
  ggtitle("Sentiment from twitter in 24 Hours", subtitle = NULL) + 
  dust_theme$theme
```

## When we like it / don't like it
```{r warning=F,message=F,echo=F}
ggplot(data = t_data, aes(x = hour, fill = sentiment)) + 
  geom_density(alpha = 0.5) + 
  dust_theme$theme + 
  scale_x_continuous(breaks = seq(0,23, 1)) +
  ggtitle("Sentiment Density", subtitle = NULL) 
```
## How do we like it
```{r warning=F,message=F,echo=F}
ggplot(subset(t_data, user_lang != "" & user_lang != "en"), aes(x = factor(1), fill = factor(user_lang))) +
  geom_bar(width = 1, position = position_fill()) + 
  coord_polar(theta = "y") +
  xlab("percentage") +
  ylab("") +
  guides(fill=guide_legend(title="language")) + 
  dust_theme$theme +
  facet_wrap(~sentiment) +
  theme(axis.text = element_blank()) +
  ggtitle("How people like it", subtitle = NULL) 
```

## What are we from
```{r warning=F,message=F,echo=F}
ggplot(t_data, aes(x = factor(1), fill = factor(user_lang))) +
  geom_bar(width = 1) + 
  coord_polar(theta = "y") +
  xlab("number of users") +
  ylab("") +
  guides(fill=guide_legend(title="language")) + 
  ggtitle("Language user speaking", subtitle = NULL) + 
  dust_theme$theme
```
```{r warning=F,message=F,echo=F, include=F}
tdata_sum <- group_by(t_data, user_lang)%>%
  summarise(
    count = n()
  )

ggplot(data = tdata_sum, aes(x = user_lang, fill = factor(count))) + 
  geom_bar(stat = "identity", aes(y = count)) + 
  dust_theme$theme +
  xlab("user language") +
  guides(fill=guide_legend(title="User Country")) 
```

## What people are taling about 
```{r warning=F,message=F,echo=F}
t_data.corpus<-Corpus(VectorSource(t_data$tweet))
##Data Cleaning and Wrangling
t_data.clean<-tm_map(t_data.corpus, PlainTextDocument)
t_data.clean<-tm_map(t_data.corpus,tolower)
t_data.clean<-tm_map(t_data.clean,removeNumbers)
t_data.clean<-tm_map(t_data.clean,removeWords,stopwords("english"))
t_data.clean<-tm_map(t_data.clean,removePunctuation)
t_data.clean<-tm_map(t_data.clean,stripWhitespace)
#t_data.clean<-tm_map(t_data.clean,stemDocument)

wordcloud(words = t_data.clean, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2")) 
```